### ISSUE TITLE
Allen Mouse atlas incorrect origin: it's ASR, but should be ASL

### ISSUE THREAD

**Issue by hadivafaii** [brainglobe/bg-atlasapi#104] opened 2021-06-18 17:24 UTC
Hi,

Allen's mouse reference space has a `PIR` orientation (+x = posterior, +y = inferior, +z = right).  This means the origin would be `ASL` (anterior, superior, left).  See [this figure](http://help.brain-map.org/download/attachments/5308472/3DOrientation.png?version=1&modificationDate=1368132564812&api=v2).

However, BG atlasapi returns them where atlas.space is `AnatomicalSpace("asr")`.  I checked metadata.json files, and they all had `orientation = "asr"`.

Code to reproduce this:

```Python
from bg_atlasapi.bg_atlas import BrainGlobeAtlas
atlas = BrainGlobeAtlas("allen_mouse_100um")
print(atlas.space)

# allen mouse atlas (res. 100um)
# From: http://www.brain-map.org (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
# <BGSpace AnatomicalSpace object>
# origin: ('Anterior', 'Superior', 'Right')
# sections: ('Frontal plane', 'Horizontal plane', 'Sagittal plane')
# shape: (132, 80, 114)

```

**Comment by vigji** [comment] 2021-06-19 07:44
Hei @hadivafaii, thank you for reporting this. I am aware of this source of confusion, and it should probably better clarified somewhere. The problem is much deeper than it might appear. The coordinate system they describe in the image is a right-handed cartesian coordinate system. Working with images and stacks, however, uses a left-handed system (images voxels are indexed top down, left right; cartesian axes are indexed bottom up, left right). You can verify that if you look at the numpy stack that contains the template brain and you use any image rendering, the (0, 0, 0) voxel in their stack is the voxel in the anterior, superior, right corner.
Note that the two systems are perfectly matching, modulo an inversion over one axis. It just depend on whether you adopt the cartesian x,y, right-handed coordinate system or the image-based, ij, left-handed coordinate system. I plan to write some more utilities in [bg-space](https://github.com/brainglobe/bg-space/tree/master/bg_space) to deal with this problem.

**Comment by hadivafaii** [comment] 2021-06-23 05:17
Thank you for your response.  I thought about this more and I still am a bit confused.  This is probably because their average template image is perfectly symmetric across the left-right axis, so it's impossible to see whether the origin is on the left or on the right.  I thought looking at an asymmetric tract-tracing experiment could help with this, so I loaded the data for [experiment 603717226](https://connectivity.brain-map.org/projection/experiment/603717226).  The injection site for this experiment is clearly on the left hemisphere which can be seen in this [cortical projection](https://connectivity.brain-map.org/projection/experiment/cortical_map/603717226) as well.

Here is a plot of data from this experiment on top of the reference image loaded from bg-atlasapi:

![allen_603717226](https://user-images.githubusercontent.com/14995982/123037988-9959a200-d3bd-11eb-8361-1b4fd28d209e.png)

As you see, the right-left direction seems to be wrong (it should say left-right).  This issue can be resolved if I use the correct space `AnatomicalSpace('asl')`.  I guess I'm being a little nit-picky since this issue doesn't really affect the main functionalities, but I want to make sure everything is alright since these libraries you have made under the brain globe umbrella are really awesome, and I will probably use them frequently.

Another issue I noticed about spaces is that I had to transform my volumetric data when I wanted to render it using brainrender.  My data was in the correct `ASL` space (I verified this separately by plotting slices) but had to do some gymnastics with it to get the results that made sense (had to apply transformations that didn't seem right: src: lsa --> tgt: asl).  Let me know if it makes more sense to post this as a separate issue over there at brainrender, or I can describe the problem with more details here.

Code to get the figure:
```Python
import numpy as np
import matplotlib.pyplot as plt


# load allen data
from allensdk.core.mouse_connectivity_cache import MouseConnectivityCache
mcc = MouseConnectivityCache(resolution=100)

experiment_id = 603717226
pjd, pjd_info = mcc.get_projection_density(experiment_id)
# dm, dm_info = mcc.get_data_mask(experiment_id)


# get bg atlase
from bg_atlasapi import BrainGlobeAtlas
atlas = BrainGlobeAtlas('allen_mouse_100um')
print(atlas.space)  # --> asr


# plot
fig, axes = plt.subplots(1, 3, figsize=(13, 4))

th = 0.01
slice_idxs = np.unravel_index(pjd.argmax(), pjd.shape)
for i, (ax, plane, labels) in enumerate(zip(axes, atlas.space.sections, atlas.space.axis_labels)):
    max_idx = slice_idxs[i]
    ax.imshow(atlas.reference.take(max_idx, i), alpha=0.4, cmap='Greys')
    
    data2plt = pjd.take(max_idx, i)
    # cond = np.logical_and(data2plt < th, dm.take(max_idx, i).astype(bool))
    cond = data2plt < th
    data2plt = np.ma.masked_where(cond, data2plt)
    im = ax.imshow(data2plt, cmap='turbo')
    plt.colorbar(im, ax=ax, shrink=0.6)
    
    ax.set_title(f"{plane.capitalize()} view\n", fontsize=17)
    ax.set_ylabel(labels[0], fontsize=13)
    ax.set_xlabel(labels[1], fontsize=13)

    _ = list(map(lambda x: x.set_visible(False), ax.spines.values()))
    ax.set_xticks([])
    ax.set_yticks([])
    
fig.tight_layout()
plt.show()
```

**Comment by vigji** [comment] 2021-06-30 16:22
Sorry for coming back at you with some delay, I had some unexpected workload to take care of.
Those spaces are always a bit confusing to think about, and I insist on the main problem: right-hand vs left-hand coordinate systems. Image-centric viewers, eg napari, or matplotlib plots, require a left-handed description of your voxel indexes. ASL and ASR are not equivalent modulo a rotation, as e.g. ASL and ALI would be; there is no rigid transformation moving from one to the other, you would need an affine with -1 determinant. We had lots of discussion at the beginning about what to use as our coordinate system. Describing this volume using the documented ASR description from the Allen will give you an inverted world every time you plot things with imshow or look at a stack with napari or fiji. This is why we decided to specify our space in a way that is immediately compatible with the conventions of those tools. On the other hand, deciding to stick with a left-handed coordinate system messes up things whenever you move to cartesian based representations, like scatterplots or rendering tools such as brainrender. Those are built with a right-handed coordinate system in mind, and transposing things there is not always trivial. For brainrender we tried with @FedeClaudi to set the coordinate system to be left-handed by default, but that was not possible. Therefore, there's an arbitrary - sign over the values of the coordinates along one of the dimensions. I guess this is what is annoying you and what we should try to figure out.

Hope I have not confused things even more! But bottom line is, you can't have a system that works out of the box in left and right -handed coordinate systems. Been quite volumes/images entered in our applications, we decided to stick to one convention at the expense of the other, but the tradeoff is inevitable as long as in the world x,y cartesian systems have the origin bottom left and i,j image systems have the origin top left...

**Comment by hadivafaii** [comment] 2021-06-30 21:33
It seems like this is more complicated than I had anticipated.  I will just try to make sense of things on my end for now.  At a later point, a permanent solution would be nice (if at all possible) since this will probably keep confusing more people like me.  Anyway, thank you very much for the detailed response, and again, for creating and sharing these libraries.

Cheers.

**Comment by adamltyson** [comment] 2021-08-06 15:28
Closing this now, feel free to reopen if we can help with anything else.

**Closed by adamltyson** 2021-08-06 15:28 UTC
