### ISSUE TITLE
Add pycln to pre-commit

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/bg-atlasapi#82] opened 2020-10-05 16:33 UTC
Hi, 

Opening it here but valid throughout the org.
We could add [pycln](https://github.com/hadialqattan/pycln) to our pre-commit stack. 
It automatically removes unused imports from all files. I have set it up in `pyinspect`  to run before `flake8` so that it fixed is before `flake8` stops the commit from going through. 

Lemme know!

**Comment by adamltyson** [comment] 2020-10-06 10:08
Duplicate of #83 :joy:

**Closed by adamltyson** 2020-10-06 10:08 UTC
